Annotaions
nerc-project/coldfront-plugin-openstack pull request #55
Opened 2022-06-15 16:01 UTC by ljmcgann

Add annotations for openshift resources.

2022-06-15 18:09 UTC, knikolla requested changes
Hi Leo, thank you for submitting this.

For reference, please, in the commit message and PR description write out the motivation for why adding these annotations to a project in OpenShift is necessary.

2022-06-15 18:09 UTC, knikolla commented on src/coldfront_plugin_openstack/openshift.py
> +logger = logging.getLogger(__name__)
For consistency, please move this above `QUOTA_KEY_MAPPING` and preserve the 2 lines of spacing between `QUOTA_KEY_MAPPING` and `ApiException` as per PEP8. I haven't added a code linter, but this would fail the linter.

2022-06-21 13:49 UTC, ljmcgann commented on src/coldfront_plugin_openstack/openshift.py
> +logger = logging.getLogger(__name__)
addressed

2022-06-21 13:49 UTC, ljmcgann commented on src/coldfront_plugin_openstack/openshift.py
> +        headers = {'Content-type': 'application/json'}
addressed

2022-06-21 13:49 UTC, ljmcgann commented on src/coldfront_plugin_openstack/openshift.py
> +        logger.warning("Removing project with url " +url)
addressed

2022-06-21 13:53 UTC, ljmcgann commented
@knikolla I have addessed the issues here

2022-06-21 15:36 UTC, ljmcgann commented
I am currently looking at the test cases outlined in https://docs.google.com/document/d/18AUzxuFWKeNOO6UFgze6Tm1mF1Gz-UIMj8Wqu6lyxcc/edit#. Specifically I am looking at deletion of allocations, which is giving me some issues

2022-06-21 15:52 UTC, joachimweyl commented
@ljmcgann I should be more specific. What are your next steps in completing this PR?

2022-06-21 15:57 UTC, joachimweyl commented
@ljmcgann supper!
@knikolla are there any other suggestions for this code?

2022-06-23 17:14 UTC, merged