Implement get_quota and initial implementation of validate_allocations
nerc-project/coldfront-plugin-openstack pull request #56
Opened 2022-06-23 17:13 UTC by knikolla

- The ResourceAllocator base class now defines get_quota and the OpenStack
resource allocator implements the method.

- Currently limited to OpenStack resources, the `validate_allocations` command
checks that the output of get_quota on an allocation, matches the value of the quota
attributes.

2022-06-27 14:21 UTC, joachimweyl commented
@knikolla is it clear what needs to be fixed/updated for test-py39-functional / build (pull_request)? Are you ready for Reviewers to be added to this PR?

2022-07-01 15:32 UTC, knikolla commented
@joachimweyl I know why the test is failing, It's on my plate to fix it in the next 2 hours.

2022-07-01 17:05 UTC, joachimweyl commented
@knikolla now that this passes the checks, is this ready for reviewers?

2022-07-06 13:48 UTC, knikolla commented on src/coldfront_plugin_openstack/management/commands/validate_allocations.py
> +                        elif not (value := quota.get(key, None)) == expected_value:
haha, any suggestions on how to better write this?

2022-07-06 17:29 UTC, larsks commented on src/coldfront_plugin_openstack/management/commands/validate_allocations.py
> +                        elif not (value := quota.get(key, None)) == expected_value:
No, this is fine, just struck me!

2022-07-11 18:28 UTC, naved001 approved these changes

2022-07-11 18:28 UTC, naved001 commented on src/coldfront_plugin_openstack/openstack.py
> +GB_IN_BYTES = 1000000000
probably just a preference thing but I would write this as `10**9` to not accidentally add more/less zeros.

2022-07-13 12:41 UTC, joachimweyl commented
@knikolla do we need @jtriley to take a look or is this ready to be merged?

2022-07-13 13:32 UTC, jtriley requested changes
LGTM just need to address the two minor comments.

2022-07-13 13:32 UTC, jtriley commented on src/coldfront_plugin_openstack/openstack.py
> +            quotas[k] = compute_quota.__getattr__(k)
Can we not use `get()` vs `__getattr__()` here for `compute_quota` and `volume_quota` as you're doing for `network_quota`?

2022-07-14 15:41 UTC, knikolla commented on src/coldfront_plugin_openstack/openstack.py
> +GB_IN_BYTES = 1000000000
Makes sense. I considered doing that.

2022-07-14 18:52 UTC, knikolla commented
@jtriley can you update your review to approved and merge?

2022-07-14 20:06 UTC, jtriley approved these changes

2022-07-14 20:07 UTC, merged