Count GPU usage
nerc-project/coldfront-plugin-openstack pull request #57
Opened 2022-06-23 18:06 UTC by knikolla

Implements the command `count_gpu_usage --flavor <flavor_name>` which
counts the number of GPU instances and compares it with the allowance.

Closes #51

2022-07-11 13:45 UTC, knikolla commented
According to https://github.com/nerc-project/nerc-docs/pull/66, there are now different types of GPU flavors. Given that this PR was written when there was only 1 GPU flavor and quota, it needs to be updated.

2022-07-11 14:21 UTC, joachimweyl commented
> According to [nerc-project/nerc-docs#66](https://github.com/nerc-project/nerc-docs/pull/66), there are now different types of GPU flavors. Given that this PR was written when there was only 1 GPU flavor and quota, it needs to be updated.

good catch!

2022-07-14 15:37 UTC, knikolla commented
@jtriley Reworked it to take `--flavor flavor1=2 --flavor flavor2=4`. I haven't had a chance to test it yet though, do you have any spare cycles to take that on?

2022-07-14 16:02 UTC, jtriley commented
@knikolla I should be able to test by end of day tomorrow at the latest. I'll report back. Thanks!

2022-07-14 16:41 UTC, jtriley requested changes

2022-07-14 16:41 UTC, jtriley commented on src/coldfront_plugin_openstack/management/commands/count_gpu_usage.py
> +            for name, index in enumerate(flavor_names):
The index comes first with the `enumerate` function so this should be:

```
for index, name in enumerate(flavor_names):
    ...
```

2022-07-14 16:41 UTC, jtriley commented on src/coldfront_plugin_openstack/management/commands/count_gpu_usage.py
> +        session = openstack.get_session_for_resource()
Need to pass in the resource object from the line before.

2022-07-14 16:43 UTC, jtriley commented
Once I put in manual fixes for those two issues I hit (I put in some print statements to show where it's at in the loop):

```
root@coldfront-deployment-debug:~# coldfront count_gpu_usage --resource NERC --flavor gpu-a100.1=1
name: gpu-a100.1
nova_flavor.name: gpu-a100.2
name: gpu-a100.1
nova_flavor.name: mem-a.8   
name: gpu-a100.1
nova_flavor.name: cpu-a.1   
name: gpu-a100.1
nova_flavor.name: cpu-a.8   
name: gpu-a100.1
nova_flavor.name: mem-a.4   
name: gpu-a100.1
nova_flavor.name: mem-a.1   
name: gpu-a100.1
nova_flavor.name: gpu-a100.4
name: gpu-a100.1
nova_flavor.name: mem-a.16  
name: gpu-a100.1
nova_flavor.name: cpu-a.16  
name: gpu-a100.1
nova_flavor.name: cpu-a.4   
name: gpu-a100.1
nova_flavor.name: gpu-a100.1
name: gpu-a100.1
nova_flavor.name: mem-a.2   
name: gpu-a100.1
nova_flavor.name: cpu-a.2   
Traceback (most recent call last):
  File "/opt/venv/bin/coldfront", line 33, in <module>
    sys.exit(load_entry_point('coldfront==1.0.4', 'console_scripts', 'coldfront')())
  File "/opt/venv/lib/python3.9/site-packages/coldfront/__init__.py", line 11, in manage
    execute_from_command_line(sys.argv)
  File "/opt/venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/opt/venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/venv/lib/python3.9/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/venv/lib/python3.9/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/opt/venv/lib/python3.9/site-packages/coldfront_plugin_openstack/management/commands/count_gpu_usage.py", line 67, in handle
    allocations = Allocation.objects.filter(
  File "/opt/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/opt/venv/lib/python3.9/site-packages/django/db/models/query.py", line 941, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/opt/venv/lib/python3.9/site-packages/django/db/models/query.py", line 961, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/opt/venv/lib/python3.9/site-packages/django/db/models/query.py", line 968, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/opt/venv/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1393, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/opt/venv/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1412, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/opt/venv/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1347, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/opt/venv/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1193, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "/opt/venv/lib/python3.9/site-packages/django/db/models/lookups.py", line 25, in __init__
    self.rhs = self.get_prep_lookup()
  File "/opt/venv/lib/python3.9/site-packages/django/db/models/fields/related_lookups.py", line 50, in get_prep_lookup
    self.rhs = [get_normalized_value(val, self.lhs)[0] for val in self.rhs]
TypeError: 'Resource' object is not iterable
```

2022-07-14 16:47 UTC, jtriley requested changes

2022-07-14 16:47 UTC, jtriley commented on src/coldfront_plugin_openstack/management/commands/count_gpu_usage.py
> +            resources__in=resource,
This needs to be a list, e.g:

```
        allocations = Allocation.objects.filter(
            resources__in=[resource],
            ...
```

2022-07-14 16:50 UTC, jtriley requested changes

2022-07-14 16:50 UTC, jtriley commented on src/coldfront_plugin_openstack/management/commands/count_gpu_usage.py
> +                    f" is using {active_gpu_count} GPU instances. (Allowed {allowed}."
Missing end-quote in the message here, e.g.:

```
                   f" is using {active_gpu_count} GPU instances. (Allowed {allowed})."
```

2022-07-14 16:51 UTC, jtriley commented
Will try some other flavors soon and verify the results

2022-07-14 18:49 UTC, knikolla commented
Thank you for massaging this to work, and sorry for not having the time to properly test it. I'll revise with the fixes tomorrow, unless you'd like to do that before then.

2022-07-14 20:04 UTC, jtriley commented
Yeah I think just better phrasing like what you suggested would be good. I can implement all of these changes and have you review. Thanks!

2022-07-14 20:09 UTC, jtriley commented
Ah on second thought I don't have access to your branch so I'll let you do it :)

2022-07-14 20:59 UTC, jtriley commented
🤷 turns out github let me make the changes in your branch so all of this has been implemented. Going to update the option parsing to assume GPU count is 1 if no count is specified and log that it's doing that via debug message.

2022-07-14 21:46 UTC, jtriley approved these changes

2022-07-14 21:49 UTC, jtriley commented
@knikolla I implemented all of the fixes discussed here in your branch. Please take a look and feel free to merge if it looks good to you.

2022-07-14 22:01 UTC, merged

2022-07-14 22:02 UTC, knikolla commented
Thanks!